In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("olist_customers_dataset.csv")

In [3]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
customers.shape

(99441, 5)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

In [6]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
customers.duplicated().sum()

np.int64(0)

In [8]:
customers["customer_unique_id"].nunique()

96096

In [9]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [10]:
customers["customer_unique_id"].value_counts().sum()

np.int64(99441)

In [11]:
customers["customer_unique_id"].value_counts().head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
dc813062e0fc23409cd255f7f53c7074     6
63cfc61cee11cbe306bff5857d00bfe4     6
f0e310a6839dce9de1638e0fe5ab282a     6
de34b16117594161a6a89c50b289d35a     6
Name: count, dtype: int64

In [12]:
orders = pd.read_csv("olist_orders_dataset.csv")

In [13]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [14]:
orders.shape

(99441, 8)

In [15]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [16]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [17]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [18]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [19]:
delivered_orders = orders[orders["order_status"] == "delivered"]

In [20]:
delivered_orders.shape

(96478, 8)

In [21]:
delivered_orders["order_purchase_timestamp"] = pd.to_datetime(
    delivered_orders["order_purchase_timestamp"]
)

In [22]:
delivered_orders.info()

<class 'pandas.DataFrame'>
Index: 96478 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96478 non-null  str
 1   customer_id                    96478 non-null  str
 2   order_status                   96478 non-null  str
 3   order_purchase_timestamp       96478 non-null  datetime64[us]
 4   order_approved_at              96464 non-null  str
 5   order_delivered_carrier_date   96476 non-null  str
 6   order_delivered_customer_date  96470 non-null  str
 7   order_estimated_delivery_date  96478 non-null  str
dtypes: datetime64[us](1), str(7)
memory usage: 20.4 MB

In [23]:
print("First purchase:", delivered_orders["order_purchase_timestamp"].min())
print("Last purchase:", delivered_orders["order_purchase_timestamp"].max())

First purchase: 2016-09-15 12:16:38
Last purchase: 2018-08-29 15:00:37

In [24]:
payments = pd.read_csv("olist_order_payments_dataset.csv")

In [25]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [26]:
payments.shape

(103886, 5)

In [27]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

In [28]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [29]:
payments.duplicated().sum()

np.int64(0)

In [30]:
payments["order_id"].nunique()

99440

In [31]:
payments["order_id"].value_counts().head(10)

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
fedcd9f7ccdc8cba3a18defedd1a5547    19
21577126c19bf11a0b91592e5844ba78    15
4bfcba9e084f46c8e3cb49b0fa6e6159    15
3c58bffb70dcf45f12bdf66a3c215905    14
4689b1816de42507a7d63a4617383c59    14
Name: count, dtype: int64

In [32]:
payment_total = payments.groupby("order_id", as_index=False)["payment_value"].sum()

In [33]:
payment_total.head()

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [34]:
payment_total.shape

(99440, 2)

In [35]:
customer_orders = delivered_orders.merge(
    customers,
    on="customer_id",
    how="left"
)

In [36]:
customer_orders.shape

(96478, 12)

In [37]:
customer_orders[[
    "customer_unique_id",
    "order_id",
    "order_purchase_timestamp",
    "customer_city",
    "customer_state"
]].head()

,customer_unique_id,order_id,order_purchase_timestamp,customer_city,customer_state
0,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,sao paulo,SP
1,af07308b275d755c9edb36a90c618231,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,barreiras,BA
2,3a653a41f6f9fc3d2a113cf8398680e8,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,vianopolis,GO
3,7c142cf63193a1473d2e66489a9ae977,949d5b44dbf5de918fe9c16f97b45f8a,2017-11-18 19:28:06,sao goncalo do amarante,RN
4,72632f0f9dd73dfee390c9b22eb56dd6,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-13 21:18:39,santo andre,SP

In [38]:
customer_data = customer_orders.merge(
    payment_total,
    on="order_id",
    how="left"
)

In [39]:
customer_data.shape

(96478, 13)

In [40]:
customer_data[[
    "customer_unique_id",
    "order_id",
    "order_purchase_timestamp",
    "payment_value"
]].head(10)

,customer_unique_id,order_id,order_purchase_timestamp,payment_value
0,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,38.71
1,af07308b275d755c9edb36a90c618231,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,141.46
2,3a653a41f6f9fc3d2a113cf8398680e8,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,179.12
3,7c142cf63193a1473d2e66489a9ae977,949d5b44dbf5de918fe9c16f97b45f8a,2017-11-18 19:28:06,72.20
4,72632f0f9dd73dfee390c9b22eb56dd6,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-13 21:18:39,28.62
5,80bb27c7c16e8f973207a5086ab329e2,a4591c265e18cb1dcee52889e2d8acc3,2017-07-09 21:57:05,175.26
6,932afa1e708222e5821dac9cd5db4cae,6514b8ad8028c9f2cc2374ded245783f,2017-05-16 13:10:30,75.16
7,39382392765b6dc74812866ee5ee92a7,76c6e866289321a7c93b82b54852dc33,2017-01-23 18:29:09,35.95
8,299905e3934e9e181bfb2e164dd4b4f8,e69bfb5eb88e0ed6a785585b27e16dbf,2017-07-29 11:55:02,169.76
9,f2a85dec752b8517b5e58a06ff3cd937,e6ce16cb79ec1d90b1da9085a6118aeb,2017-05-16 19:41:10,259.06

In [41]:
customer_data["payment_value"].isnull().sum()

np.int64(1)

In [42]:
customer_data[customer_data["payment_value"].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_value
29811,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,830d5b7aaa3b6f1e9ad63703bec97d23,14600,sao joaquim da barra,SP,NaN

In [43]:
customer_data = customer_data.dropna(subset=["payment_value"])

In [44]:
customer_data.shape

(96477, 13)

In [45]:
customer_data["customer_unique_id"].nunique()

93357

In [46]:
analysis_date = customer_data["order_purchase_timestamp"].max() + pd.Timedelta(days=1)

analysis_date

Timestamp('2018-08-30 15:00:37')

In [47]:
last_purchase = customer_data.groupby("customer_unique_id")["order_purchase_timestamp"].max()

last_purchase.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2   2018-05-10 10:56:27
0000b849f77a49e4a4ce2b2a4ca5be3f   2018-05-07 11:11:27
0000f46a3911fa3c0805444483337064   2017-03-10 21:05:03
0000f6ccb0745a6a4b88665a16c9f078   2017-10-12 20:29:41
0004aac84e0df4da2b147fca70cf8255   2017-11-14 19:45:42
Name: order_purchase_timestamp, dtype: datetime64[us]

In [48]:
recency = (analysis_date - last_purchase).dt.days

recency.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    112
0000b849f77a49e4a4ce2b2a4ca5be3f    115
0000f46a3911fa3c0805444483337064    537
0000f6ccb0745a6a4b88665a16c9f078    321
0004aac84e0df4da2b147fca70cf8255    288
Name: order_purchase_timestamp, dtype: int64

In [49]:
frequency = customer_data.groupby("customer_unique_id")["order_id"].nunique()

frequency.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
Name: order_id, dtype: int64

In [50]:
monetary = customer_data.groupby("customer_unique_id")["payment_value"].sum()

monetary.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f     27.19
0000f46a3911fa3c0805444483337064     86.22
0000f6ccb0745a6a4b88665a16c9f078     43.62
0004aac84e0df4da2b147fca70cf8255    196.89
Name: payment_value, dtype: float64

In [51]:
rfm = pd.DataFrame({
    "Recency": recency,
    "Frequency": frequency,
    "Monetary": monetary
})

rfm.head()

                                  Recency  Frequency  Monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     27.19
0000f46a3911fa3c0805444483337064      537          1     86.22
0000f6ccb0745a6a4b88665a16c9f078      321          1     43.62
0004aac84e0df4da2b147fca70cf8255      288          1    196.89

In [52]:
rfm.shape

(93357, 3)

In [53]:
rfm.describe()

            Recency     Frequency      Monetary
count  93357.000000  93357.000000  93357.000000
mean     237.936673      1.033420    165.198772
std      152.584315      0.209099    226.314579
min        1.000000      1.000000      9.590000
25%      114.000000      1.000000     63.060000
50%      219.000000      1.000000    107.780000
75%      346.000000      1.000000    182.560000
max      695.000000     15.000000  13664.080000

In [54]:
rfm["Frequency"].value_counts().sort_index()

Frequency
1     90556
2      2573
3       181
4        28
5         9
6         5
7         3
9         1
15        1
Name: count, dtype: int64

In [55]:
repeat_customers = (rfm["Frequency"] > 1).sum()

repeat_rate = (repeat_customers / len(rfm)) * 100

print("Repeat Customers:", repeat_customers)
print("Repeat Customer Rate:", round(repeat_rate, 2), "%")

Repeat Customers: 2801
Repeat Customer Rate: 3.0 %

In [56]:
rfm["Recency"].quantile([0.25, 0.50, 0.75])

0.25    114.0
0.50    219.0
0.75    346.0
Name: Recency, dtype: float64

In [57]:
rfm["Monetary"].quantile([0.25, 0.50, 0.75])

0.25     63.06
0.50    107.78
0.75    182.56
Name: Monetary, dtype: float64

In [58]:
rfm[rfm["Frequency"] > 1]["Frequency"].describe()

count    2801.000000
mean        2.113888
std         0.503796
min         2.000000
25%         2.000000
50%         2.000000
75%         2.000000
max        15.000000
Name: Frequency, dtype: float64

In [59]:
def frequency_score(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    elif x <= 4:
        return 3
    else:
        return 4

rfm["F_Score"] = rfm["Frequency"].apply(frequency_score)

In [60]:
rfm["F_Score"].value_counts().sort_index()

F_Score
1    90556
2     2573
3      209
4       19
Name: count, dtype: int64

In [61]:
def recency_score(x):
    if x <= 114:
        return 4
    elif x <= 219:
        return 3
    elif x <= 346:
        return 2
    else:
        return 1

rfm["R_Score"] = rfm["Recency"].apply(recency_score)

In [62]:
rfm["R_Score"].value_counts().sort_index()

R_Score
1    23310
2    23200
3    23451
4    23396
Name: count, dtype: int64

In [63]:
def monetary_score(x):
    if x <= 63.06:
        return 1
    elif x <= 107.78:
        return 2
    elif x <= 182.56:
        return 3
    else:
        return 4

rfm["M_Score"] = rfm["Monetary"].apply(monetary_score)

In [64]:
rfm["M_Score"].value_counts().sort_index()

M_Score
1    23341
2    23339
3    23338
4    23339
Name: count, dtype: int64

In [65]:
rfm.head(10)

,Recency,Frequency,Monetary,F_Score,R_Score,M_Score
customer_unique_id,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,1,4,3
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,1,3,1
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,1,2,1
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,1,2,4
0004bd2a26a76fe21f786e4fbd80607f,146,1,166.98,1,3,3
00050ab1314c0e55a6ca13cf7181fecf,132,1,35.38,1,3,1
00053a61a98854899e70ed204dd4bafe,183,1,419.18,1,3,4
0005e1862207bf6ccc02e4228effd9a0,543,1,150.12,1,1,3
0005ef4cd20d2893f0d9fbd94d3c0d97,170,1,129.76,1,3,3

In [66]:
rfm = rfm[[
    "Recency",
    "Frequency",
    "Monetary",
    "R_Score",
    "F_Score",
    "M_Score"
]]

rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score
customer_unique_id,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,3
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,3,1,1
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4

In [67]:
rfm["RFM_Code"] = (
    rfm["R_Score"].astype(str) +
    rfm["F_Score"].astype(str) +
    rfm["M_Score"].astype(str)
)

rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code
customer_unique_id,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,3,413
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,3,1,1,311
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214

In [68]:
pd.crosstab(
    rfm["R_Score"],
    rfm["F_Score"]
)

F_Score      1    2   3  4
R_Score
1        22731  537  41  1
2        22527  629  43  1
3        22685  700  57  9
4        22613  707  68  8

In [69]:
def assign_segment(row):
    R = row["R_Score"]
    F = row["F_Score"]
    M = row["M_Score"]

    # Repeat customers
    if R >= 3 and F >= 3 and M >= 3:
        return "Champions"

    elif R >= 3 and F >= 2:
        return "Loyal Customers"

    elif R <= 2 and F >= 2:
        return "At Risk"

    # One-time customers
    elif R == 4 and F == 1:
        return "Recent Customers"

    elif F == 1 and M == 4:
        return "High-Value One-Time"

    elif R == 3 and F == 1:
        return "Promising"

    elif R == 2 and F == 1:
        return "Needs Attention"

    else:
        return "Inactive"


rfm["Segment"] = rfm.apply(assign_segment, axis=1)

In [70]:
rfm["Segment"].value_counts()

Segment
Recent Customers       22613
Inactive               17379
Promising              17255
Needs Attention        17218
High-Value One-Time    16091
Loyal Customers         1408
At Risk                 1252
Champions                141
Name: count, dtype: int64

In [71]:
segment_summary = rfm.groupby("Segment").agg(
    Customers=("Frequency", "size"),
    Avg_Recency=("Recency", "mean"),
    Avg_Frequency=("Frequency", "mean"),
    Avg_Monetary=("Monetary", "mean"),
    Total_Revenue=("Monetary", "sum")
).reset_index()

segment_summary

,Segment,Customers,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue
0,At Risk,1252,353.091054,2.079073,300.982404,376829.97
1,Champions,141,105.723404,3.553191,542.109362,76437.42
2,High-Value One-Time,16091,298.507551,1.000000,387.752746,6239329.43
3,Inactive,17379,451.332010,1.000000,87.275356,1516758.41
4,Loyal Customers,1408,113.684659,2.000710,291.967202,411089.82
5,Needs Attention,17218,277.038042,1.000000,89.260420,1536885.92
6,Promising,17255,166.833903,1.000000,89.370930,1542095.39
7,Recent Customers,22613,57.500774,1.000000,164.641375,3723035.41

In [72]:
segment_summary["Customer_%"] = (
    segment_summary["Customers"] / segment_summary["Customers"].sum() * 100
)

segment_summary["Revenue_%"] = (
    segment_summary["Total_Revenue"] / segment_summary["Total_Revenue"].sum() * 100
)

segment_summary[[
    "Segment",
    "Customers",
    "Customer_%",
    "Avg_Recency",
    "Avg_Frequency",
    "Avg_Monetary",
    "Total_Revenue",
    "Revenue_%"
]].sort_values("Total_Revenue", ascending=False)

,Segment,Customers,Customer_%,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue,Revenue_%
2,High-Value One-Time,16091,17.235987,298.507551,1.000000,387.752746,6239329.43,40.456119
7,Recent Customers,22613,24.222072,57.500774,1.000000,164.641375,3723035.41,24.140345
6,Promising,17255,18.482813,166.833903,1.000000,89.370930,1542095.39,9.999022
5,Needs Attention,17218,18.443180,277.038042,1.000000,89.260420,1536885.92,9.965244
3,Inactive,17379,18.615637,451.332010,1.000000,87.275356,1516758.41,9.834736
4,Loyal Customers,1408,1.508189,113.684659,2.000710,291.967202,411089.82,2.665527
0,At Risk,1252,1.341089,353.091054,2.079073,300.982404,376829.97,2.443384
1,Champions,141,0.151033,105.723404,3.553191,542.109362,76437.42,0.495624

In [73]:
segment_actions = {
    "Champions": "Retain with VIP rewards and exclusive offers",
    "Loyal Customers": "Strengthen loyalty and encourage higher spend",
    "Recent Customers": "Encourage a second purchase",
    "Promising": "Nurture with personalized recommendations",
    "High-Value One-Time": "Target for repeat purchase and loyalty conversion",
    "Needs Attention": "Re-engage before they become inactive",
    "At Risk": "Run targeted win-back campaigns",
    "Inactive": "Use selective reactivation campaigns"
}

rfm["Recommended_Action"] = rfm["Segment"].map(segment_actions)

In [74]:
rfm[[
    "Recency",
    "Frequency",
    "Monetary",
    "R_Score",
    "F_Score",
    "M_Score",
    "Segment",
    "Recommended_Action"
]].head(10)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,Segment,Recommended_Action
customer_unique_id,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,3,Recent Customers,Encourage a second purchase
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,3,1,1,Promising,Nurture with personalized recommendations
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,Inactive,Use selective reactivation campaigns
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,Needs Attention,Re-engage before they become inactive
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,High-Value One-Time,Target for repeat purchase and loyalty conversion
0004bd2a26a76fe21f786e4fbd80607f,146,1,166.98,3,1,3,Promising,Nurture with personalized recommendations
00050ab1314c0e55a6ca13cf7181fecf,132,1,35.38,3,1,1,Promising,Nurture with personalized recommendations
00053a61a98854899e70ed204dd4bafe,183,1,419.18,3,1,4,High-Value One-Time,Target for repeat purchase and loyalty conversion
0005e1862207bf6ccc02e4228effd9a0,543,1,150.12,1,1,3,Inactive,Use selective reactivation campaigns
0005ef4cd20d2893f0d9fbd94d3c0d97,170,1,129.76,3,1,3,Promising,Nurture with personalized recommendations

In [75]:
rfm = rfm.reset_index()

In [76]:
rfm.head()

,customer_unique_id,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,Segment,Recommended_Action
0,0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,3,413,Recent Customers,Encourage a second purchase
1,0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,3,1,1,311,Promising,Nurture with personalized recommendations
2,0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,Inactive,Use selective reactivation campaigns
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,Needs Attention,Re-engage before they become inactive
4,0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,High-Value One-Time,Target for repeat purchase and loyalty conversion

In [78]:
rfm.shape

(93357, 11)

In [79]:
rfm.columns.tolist()

['index',
 'customer_unique_id',
 'Recency',
 'Frequency',
 'Monetary',
 'R_Score',
 'F_Score',
 'M_Score',
 'RFM_Code',
 'Segment',
 'Recommended_Action']

In [80]:
rfm.drop(columns=["index"], inplace=True)

In [81]:
rfm.shape

(93357, 10)

In [82]:
customer_location = (
    customer_data
    .sort_values("order_purchase_timestamp")
    .groupby("customer_unique_id")
    .tail(1)
    [["customer_unique_id", "customer_city", "customer_state"]]
)

customer_location.head()

                     customer_unique_id customer_city customer_state
27599  2f64e403852e6893ae37485d5fcacdaf       panambi             RS
95059  61db744d2f835035a5625b59350c6b63  porto alegre             RS
85830  8d3a54507421dbd2ce0a1d58046826e0   hortolandia             SP
6552   87776adb449c551e74c13fc34f036105       taubate             SP
60299  7390ed59fa1febbfda31a80b4318c8cb   mozarlandia             GO

In [83]:
customer_location.shape

(93357, 3)

In [84]:
customer_location["customer_unique_id"].nunique()

93357

In [85]:
rfm = rfm.merge(
    customer_location,
    on="customer_unique_id",
    how="left"
)

In [86]:
print("Shape:", rfm.shape)
print("Unique customers:", rfm["customer_unique_id"].nunique())
print("Missing city:", rfm["customer_city"].isnull().sum())
print("Missing state:", rfm["customer_state"].isnull().sum())

Shape: (93357, 12)
Unique customers: 93357
Missing city: 0
Missing state: 0

In [87]:
print("Duplicate customers:", rfm["customer_unique_id"].duplicated().sum())

print("\nMissing values:")
print(rfm.isnull().sum())

print("\nSegment total:")
print(rfm["Segment"].value_counts().sum())

print("\nRFM ranges:")
print(rfm[["Recency", "Frequency", "Monetary"]].agg(["min", "max"]))

Duplicate customers: 0

Missing values:
customer_unique_id    0
Recency               0
Frequency             0
Monetary              0
R_Score               0
F_Score               0
M_Score               0
RFM_Code              0
Segment               0
Recommended_Action    0
customer_city         0
customer_state        0
dtype: int64

Segment total:
93357

RFM ranges:
     Recency  Frequency  Monetary
min        1          1      9.59
max      695         15  13664.08

In [88]:
rfm.to_csv(
    "olist_customer_segmentation_final.csv",
    index=False
)

In [89]:
import os

print(os.path.exists("olist_customer_segmentation_final.csv"))

True

In [90]:
rfm.head()

,customer_unique_id,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,Segment,Recommended_Action,customer_city,customer_state
0,0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,3,413,Recent Customers,Encourage a second purchase,cajamar,SP
1,0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,3,1,1,311,Promising,Nurture with personalized recommendations,osasco,SP
2,0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,Inactive,Use selective reactivation campaigns,sao jose,SC
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,Needs Attention,Re-engage before they become inactive,belem,PA
4,0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,High-Value One-Time,Target for repeat purchase and loyalty conversion,sorocaba,SP